### ISSUE TITLE
plan to charge or be free?

### ISSUE THREAD

**Issue by mingzepeng** [sablejs/sablejs#1]

**Comment by ErosZy** [comment]
@mingzepeng 类似tinypng，分为免费/会员收费，免费有上传次数限制和代码大小限制，会员没有此类限制。
编译期闭源，解释器混淆后公开，客户端执行编译。

**Comment by mingzepeng** [comment]
> @mingzepeng 类似tinypng，分为免费/会员收费，免费有上传次数限制和代码大小限制，会员没有此类限制。
> 编译器闭源，解释器混淆后公开，客户端本地执行编译。

好的,谢谢
