### ISSUE TITLE
如何调用js里的方法

### ISSUE THREAD

**Issue by he1937228092** [sablejs/sablejs#12]
大佬 你好
假设我的js如下
function sign(data) {
    //进行签名算法
    return data;
}
编译后我如何通vm调用这个sign算法并传参呢

**Comment by ErosZy** [comment]
// your external js
function sign(data){
  // something should be done
  return data;
}

const global = vm.getGlobal();
const vSign = vm.createFunction("sign", function(data){
    const signStr = sign(vm.asString(data));
    return vm.createString(signStr);
})

vm.setProperty(global, "sign");
vm.run();

// inside vm
sign("Hello World!");

you can follow: https://github.com/sablejs/ajax4sablejs or [Quick Start](https://github.com/sablejs/sablejs#example) to get more detail.

**Comment by he1937228092** [comment]
![image](https://user-images.githubusercontent.com/64998502/128987924-032388fd-703f-4d54-b02c-1eba68a0836c.png)
![image](https://user-images.githubusercontent.com/64998502/128987955-ace79dac-3945-4ef7-b969-b739425ae9f6.png)
我按照你的写法一运行就会出错  不知道哪里有问题

**Comment by he1937228092** [comment]
![image](https://user-images.githubusercontent.com/64998502/128988301-97fe2195-6c3f-4117-ba2d-64098297616d.png)
![image](https://user-images.githubusercontent.com/64998502/128988321-5822c58c-72a0-4038-8a0d-4d6c6ca7e340.png)
我按照你的运行后提示这个  不知道是哪里的问题

**Comment by ErosZy** [comment]
> ![image](https://user-images.githubusercontent.com/64998502/128988301-97fe2195-6c3f-4117-ba2d-64098297616d.png)
> ![image](https://user-images.githubusercontent.com/64998502/128988321-5822c58c-72a0-4038-8a0d-4d6c6ca7e340.png)
> 我按照你的运行后提示这个 不知道是哪里的问题

Code update

**Comment by he1937228092** [comment]
![image](https://user-images.githubusercontent.com/64998502/128993624-5716fe41-da47-42da-a9d2-c5d0ed25456e.png)
我是这样的 调用提示sign不是函数

**Comment by he1937228092** [comment]
![image](https://user-images.githubusercontent.com/64998502/128993722-33c3123f-3208-40ad-98ed-5ab315607287.png)
![image](https://user-images.githubusercontent.com/64998502/128993776-73d355c7-b6c4-4409-a096-dbede71f035f.png)

我是这样的   无法跑起来

**Comment by ErosZy** [comment]
Hi @he1937228092 , you should define sign at your `index` function.

**Comment by he1937228092** [comment]
![image](https://user-images.githubusercontent.com/64998502/128999561-63723ed7-038f-48c9-9d01-1b4bf5f9a779.png)
![image](https://user-images.githubusercontent.com/64998502/128999698-7cf86990-c7fd-4405-991a-33bfe1308ba0.png)
我用的vue  你的意思是我在生命周期中创建vm然后index里调用吗？我改成这样一样报错，原谅我的无知  哈哈

**Comment by he1937228092** [comment]
能给分完整的代码吗 研究一天了  大佬

**Comment by ErosZy** [comment]
```javascript
// you should have sign function like this
function sign(data){
   return data || "";
}

export default {
   data(){
     return {};
   },
  // ignore your code
}
```

**Comment by he1937228092** [comment]
直接把sign方法写在页面中，这样不相当于没有加密吗

**Comment by ErosZy** [comment]
@he1937228092 , if you want to protect sign function implement, Quick Start should have been show you. For your example:
1. inside vm, you should implement `sign` function like this:
```javascript
// inside vm
function sign(data){
   return data + ", do what you want";
}
```

2. compile vm code, you can follow by sablejs document.
3. call your vm code, like this:
```javascript
const global = vm.getGlobal();
const vSign = vm.getProperty(global, "sign");
const vResult = vm.call(vSign, global, vm.createString("Hello World!"));
const result = vm.asString(vResult);
console.log(result); // Hello World, do what you want.
```

you can follow Quick Start to get more detail.
