### ISSUE TITLE
可以支持微信小程序么

### ISSUE THREAD

**Issue by mingzepeng** [sablejs/sablejs#16]
可以支持微信小程序么

**Comment by ErosZy** [comment]
if you have any issues, please reopen, thanks

**Comment by mingzepeng** [comment]
if I do not use ajax, could I need to binding it by myself

**Comment by mingzepeng** [comment]
i met up with another problem; mini program  does not support atob, but your vm source code use atob. can the vm add an api to custom atob  api  like this
```
const VM = require("sablejs/runtime")();
VM.custom('atob',(str)=>{
// atob polyfill  code here
})
```

**Comment by ErosZy** [comment]
@mingzepeng we don't need to add custom, we have a `-j` to ouput simple json data, like:
```shell
> sablejs -j -i your.js -o output.json 
```

then, we just pass `true` to VM.prototype.run, like:
```javascript
vm.run(data, true); // data is simple json using -j
```

i will update doc, thanks, mingze.

**Comment by ErosZy** [comment]
if you have any issues, please reopen, thanks.
