### ISSUE TITLE
Open-source without source?

### ISSUE THREAD

**Issue by dizys** [sablejs/sablejs#20]
`runtime.js` is unfortunately very compressed.
Is this project open-sourced in any way? Or this is just a repo for the final npm artifacts?
Thank you for the work. But as this is pretty much MIT-ish licensed, without source code, hardly can we trust any project with it.

**Comment by ErosZy** [comment]
sablejs 1.x is not based MIT-ish licensed.
> Non-profit projects of individuals or organizations and commercial projects with commercial authorization of the author.

And why sablejs 1.x can't be opened all code, 2.0 can be, please refer https://github.com/sablejs/sablejs/issues/19

**Comment by ErosZy** [comment]
if you have any problem, please reopen it, thanks.
