### ISSUE TITLE
VM中能否支持SM4加密算法，实际操作中发现会抛异常。

### ISSUE THREAD

**Issue by panchaowu** [sablejs/sablejs#25]
runtime.js:1 Uncaught Error: Uncaught TypeError: string is not callable
    at au (runtime.js:1)
    at as (runtime.js:1)
    at aC (runtime.js:1)
    at eg (runtime.js:1)

**Comment by ErosZy** [comment]
Can you provide the minimal project that can reproduce this issue?

**Comment by panchaowu** [comment]
> Can you provide the minimal project that can reproduce this issue?

当我通过sablejs编译这段js时，会出现编译错误。
[demo.txt](https://github.com/sablejs/sablejs/files/8312641/demo.txt)

**Comment by ErosZy** [comment]
@panchaowu 
```javascript
var sm4=new SM4Util();
let encryptDataCBC = sm4.encryptData_CBC('this is a test'); // 'let' should be 'var'
console.log(encryptDataCBC)
```

there is my compiled result.
[output.txt](https://github.com/sablejs/sablejs/files/8313952/output.txt)

**Comment by panchaowu** [comment]
> @panchaowu
> 
> ```js
> var sm4=new SM4Util();
> let encryptDataCBC = sm4.encryptData_CBC('this is a test'); // 'let' should be 'var'
> print(encryptDataCBC); // 'console' and 'alert' not included in vm, so you should use 'print' instead
> ```
> 
> modify and run it, you will get
> 
> ```js
> key error!
> iv error!
> prbpqTP2HDcvvm9snbKC9Q==
> ```
> 
> there is my original code and compiled result.
> 
> [code.txt](https://github.com/sablejs/sablejs/files/8314016/code.txt)
> 
> [output.txt](https://github.com/sablejs/sablejs/files/8314019/output.txt)
> 
> if you have any other problem, please reopen it, thanks.

多谢，

> @panchaowu
> 
> ```js
> var sm4=new SM4Util();
> let encryptDataCBC = sm4.encryptData_CBC('this is a test'); // 'let' should be 'var'
> print(encryptDataCBC); // 'console' and 'alert' not included in vm, so you should use 'print' instead
> ```
> 
> modify and run it, you will get
> 
> ```js
> key error!
> iv error!
> prbpqTP2HDcvvm9snbKC9Q==
> ```
> 
> there is my original code and compiled result.
> 
> [code.txt](https://github.com/sablejs/sablejs/files/8314016/code.txt)
> 
> [output.txt](https://github.com/sablejs/sablejs/files/8314019/output.txt)
> 
> if you have any other problem, please reopen it, thanks.

多谢。顺便问一下，sablejs 2.0预计什么时间可以开源出来呢
