### ISSUE TITLE
@zdrin If you want to new EventDispatcher, you should bind cax to sablejs, like cax4sablejs doc said:

### ISSUE THREAD

**Issue by panchaowu** [sablejs/sablejs#28]
@zdrin If you want to new EventDispatcher, you should bind cax to sablejs, like cax4sablejs doc said: 
```javascript
const cax4sablejs = require("cax4sablejs");
const VM = require("sablejs/runtime")();
const vm = new VM();
cax4sablejs(vm); // that's all!
```
If you want to call sablejs inner function from outside, you can use `vm.call`, for example:
```javascript
// a function is on sablejs inner enviorment
function a(){
  print('a');
}
```

```javascript
// get sablejs inner function and call it
const global = vm.getGlobal();
const vA = vm.getProperty(global, 'a');
vm.call(vA, vm.createUndefined()); // will log 'a'
```

_Originally posted by @ErosZy in https://github.com/sablejs/sablejs/issues/10#issuecomment-855211622_

**Comment by panchaowu** [comment]
我参照你上面的写法去写的，会报如下错误：
Uncaught Error: Uncaught TypeError: undefined is not callable
    at au (runtime.js:1:20099)
    at as (runtime.js:1:19720)
    at aC (runtime.js:1:26783)
    at ef.call (runtime.js:1:220736)

**Comment by ErosZy** [comment]
@panchaowu please upload the minimal and whole code.

**Comment by panchaowu** [comment]
我已经找到问题点了，多谢回复。顺便问下，sablejs 2.0预计什么是否可以开源出来呢

**Comment by ErosZy** [comment]
@panchaowu not sure.
