### ISSUE TITLE
能否支持commonjs/umd的模块导出

### ISSUE THREAD

**Issue by zenxds** [sablejs/sablejs#30]
一般自己打包后的代码，或者很多第三方库都是umd导出的，能否提供支持在run之后直接返回导出的内容，这样在易用性上和对现有项目的兼容上会好很多。

举一个场景，在一个项目里，只对不涉及dom的语言或者加密算法模块进行保护，其他模块不需要改动。

**Comment by ErosZy** [comment]
it's a good idea, but sablejs doesn't only support protect ecma5.1 code, and write for sandbox....so, we may not support this feature.
