### ISSUE TITLE
Compiler source code / Redistribute MacOS compiler binary

### ISSUE THREAD

**Issue by neomafo88** [sablejs/sablejs#33]
The distributed binary for MacOS `sablejs-osx-x64`, doesn't seem to work for me on macOS 12.5.1.
It runs and terminates with exit code 4, producing no output file.
I verified that it is not something wrong with the JavaScript input file - compiling it on Linux using the supplied binary on Ubuntu 20.04 works properly.

Can't seem to find the source code to self-compile my own binary.
Is it made public somewhere?
Otherwise, recompile & redistribute the MacOS binary, after verifying if it is indeed broken somewhere.

Attached [sablejs-osx-x64.zip](https://github.com/sablejs/sablejs/files/9540818/sablejs-osx-x64.zip)

**Comment by ErosZy** [comment]
@neomafo88 please try 1.1.0

**Comment by ErosZy** [comment]
if you have other issue, please reopen it, thx.
