### ISSUE TITLE
关于浏览器环境下的配置

### ISSUE THREAD

**Issue by zdrin** [sablejs/sablejs#9]
您好，看您在介绍中，浏览器环境下的代码中有：const VM = require("sablejs/runtime")();
我要做的就是加密网站中的JS代码
但我在实际测试中，浏览器控制台提示无法使用require，然后创建require变量后，说require不是函数，改成了require("runtime.js文件路径")，然后console.log(VM)的时候反馈undefined。
所以，想咨询一下，不是在node.js下，而是作为加密网站JS代码功能使用的时候，我做错了什么呢？菜鸟一枚，多谢指教！

**Comment by jiyinyiyong** [comment]
打包工具 webpack vite 了解一下

**Comment by ErosZy** [comment]
> 浏览器控制台提示无法使用require，然后创建require变量后，说require不是函数，改成了require("runtime.js文件路径")

If you need to use `require` on browser enviorment, you should use webpack/parcel/vite... to package your code. But you can import `runtime` directly:
```html
<script src="https://cdn.jsdelivr.net/npm/sablejs@1.0.3/runtime.js"></script>
<script>
    const VM = sablejs();
    // do what you want...
</script>
```
> 然后console.log(VM)的时候反馈undefined

Because sablejs only support `sandbox` mode now, please follow this issue: https://github.com/sablejs/sablejs/issues/2
